### ISSUE TITLE
Readme: Update existing records

### ISSUE THREAD

**Issue by Jpsy** [derhansen/sf_event_mgt_extend_demo#1]
Thanks for this great demo. It helped me a lot in adding my own custom fields.
The only step that gave me a hard time was this section in the README.md:

> Update existing records
> 
> If your TYPO3 installation does already contain events or registrations, make sure to update existing records so the new field "Record type" is set.

Not being very involved with adding new fields in Extbase extensions, I had problems to figure out what field "Record type" would mean. In fact I found out that the field in the table is called "tx_extbase_type".

Here is a proposal for a replacement text that would IMHO make things clearer:

> Update existing records
> 
> If your TYPO3 installation does already contain events or registrations, make sure to update existing records so the new field "tx_extbase_type" (the so called "Record type") is set in each table that you extend. 
> Use a database management tool like phpMyAdmin to adjust the field. The value needed depends on the name of your extension and the extended model. For this demo extension the correct values are:
> For the Events table: "Tx_SfEventMgtExtendDemo_Event" 
> For the Registrations table: "Tx_SfEventMgtExtendDemo_Registration"
> The easiest way to derived the correct value for your table is to create one new record and to look the value up in the "tx_extbase_type" field of this record. Then copy it to all existing records.

**Comment by derhansen** [comment]
Thanks, I've just updated the README.md file.
