### ISSUE TITLE
TYPO3 10.4 compatible version available soon?

### ISSUE THREAD

**Issue by wini2** [derhansen/sf_event_mgt_extend_demo#10]
Hi,

the demo leads to error in conjunction with TYPO3 10.4 and sf_event_mgt 5.0 - probablily because the demoversion 0.3.0 is not suitable to TYPO3 10.

do you plan to do release a adapted version in the near future?

**Comment by derhansen** [comment]
A version will be available at some time, but I'm afraid not "soon" or in the "near future".

**Comment by derhansen** [comment]
See https://github.com/derhansen/sf_event_mgt_extend_demo/releases/tag/0.4.0
