### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by blackbasket** [derhansen/sf_event_mgt_extend_demo#12]
I am unable to see any label for my new fields from extend-demo...

i.e. not working:
`<f:form.checkbox id="hotelRoomNeeded" property="hotelRoomNeeded" value="1"/>
                      <f:translate key="tx_sfeventmgtextenddemo_domain_model_registration.hotelRoomNeeded"/>
                      <e:registration.isRequiredField settings="{settings}" fieldname="hotelRoomNeeded">
                        <span class="event-required">*</span>
                      </e:registration.isRequiredField><br>
                    <f:render partial="FormErrors" arguments="{field: 'registration.hotelRoomNeeded'}"/>`

I cannot see the english label as well as the german label translated with the translate_locallang extension.

**Comment by derhansen** [comment]
When you use `<f:translate>` in views of the "main" extension, the scope is always within `sf_event_mgt`. So all localizations are looked up in the translation files of that extension. 

So when you extend the extension as shown in this demo extension, you can either add your own/new language labels to the translation files of `sf_event_mgt` (either by TypoScript or as shown in the FAQ in the documentation of `sf_event_mgt`) or add them in the extending extension and ensure you set the `extensionName` in `<f:translate>` properly as shown below:

```
<f:translate key="tx_sfeventmgtextenddemo_domain_model_registration.hotel_room_needed" extensionName="sf_event_mgt_extend_demo" />
```

**Comment by blackbasket** [comment]
Thank you, it is working now :)
