### ISSUE TITLE
Feature request: a foreign table example 

### ISSUE THREAD

**Issue by j-lang** [derhansen/sf_event_mgt_extend_demo#13]
A sample like the original organizer field referencing an external table would be great!

**Comment by derhansen** [comment]
This extension is just for demonstration purposes and I will not add additional features or examples. 

I suggest you to either search for tutorials on how to extend existing Extbase models (e.g. use a search engine and search for "typo3 overwrite model") or to ask either on stackoverflow.com (tag you question with "TYPO3") or TYPO3 slack for help.
