### ISSUE TITLE
Extending sf_event_mgt fails for php 7

### ISSUE THREAD

**Issue by saneinsane** [derhansen/sf_event_mgt_extend_demo#3]
Overriding the controller method "saveRegistrationAction" leads to error "PHP Warning: Declaration of … should be compatible with..." when using php7. Is there a workaround for this?
(https://github.com/derhansen/sf_event_mgt_extend_demo/blob/master/Classes/Controller/EventController.php#L42)

**Comment by derhansen** [comment]
I will add an interface for the `Registration`, so extending the registration class will be possible. 

See: https://github.com/derhansen/sf_event_mgt/issues/429

**Comment by derhansen** [comment]
I refactored the whole example extension, so it works without any problems with PHP7. I decided to recommend `ext:extender`, which offers an easy way of extending existing Extbase domain models.

I'll close this issue. If you have any additional questions, feed free to contact me.
