### ISSUE TITLE
No labels in BE

### ISSUE THREAD

**Issue by Hobokens** [derhansen/sf_event_mgt_extend_demo#5]
Hi Torben,
thanks for the nice demo to extend sf_event_mgt. The new fields are added in the BE and in the table but there are no labels. I use typo3 8.7.8.

Regards
Hobokens
![no lables typo3 cms 8 7 8](https://user-images.githubusercontent.com/6764582/31913654-19b69812-b848-11e7-843e-0a9a9fdb25ca.png)

**Comment by derhansen** [comment]
Hi Hobokens,

I tried to reproduce the problem with no success. The language label gets rendered as it should (for german language, it uses the english fallback).

Could you please try the clear the cache completely?

Best regards
Torben

**Comment by Hobokens** [comment]
Hi Torben,
thanks for your answer. I checked my system again (TYPO3 8.7.7), uninstalled and reinstalled the 'original' sf_event_mgt_extend_demo  and cleared the cache in the install tool. But I'm still missing the labels in the BE. 
It's not a big problem for me because I just replace the labels in the TCA with my own strings without using the language folder.

Best regards
Hobokens

**Comment by derhansen** [comment]
OK, thanks for feedback. I'm closing the issue. If you still have problems with language labels in combination with extended fields, feel free to contact me.
