### ISSUE TITLE
not loadable in extension-builder

### ISSUE THREAD

**Issue by netzteil** [derhansen/sf_event_mgt_extend_demo#7]

**Comment by netzteil** [comment]
Ahoi, derhansen,
I would have liked to understand the process of extend the extension with some Fields.
Regrettably the demo-pack does not load in extension-builder. The necessary files are missing.
May be the zip is corrupted?

Greets.

**Comment by derhansen** [comment]
I removed extension builder files. It is always a good point to start extending other extensions with extension_builder, but at some point (at least when you modify models/repositories/TCA yourself), I would not recommend to use extension_builder any more.
